FROM mongo:latest

# Set time zone (mongo image is Debian-based)
RUN apt-get update && apt-get install -y --no-install-recommends tzdata && \
    echo "{{ docker_container_timezone }}" > /etc/timezone && \
    rm -f /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
