FROM nginx:alpine

# Install bash
RUN apk update && apk upgrade && \
    apk add --no-cache bash

# Set time zone
RUN apk --no-cache add tzdata && \
    cp "/usr/share/zoneinfo/{{ docker_container_timezone }}" /etc/localtime && \
    apk del tzdata

# Install optional package
RUN apk add --no-cache openssl
